version: '3.1'

services:

  db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: alumnos
        MYSQL_USER: javier
        MYSQL_PASSWORD: root
    volumes:
      - ./my/mysql:/etc/mysql/conf.d
      - ./database:/var/lib/mysql
    ports:
      - "3307:3306"
 
