version: '3.1'
services:

  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: "ejemplo"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "javier" 
      MYSQL_PASSWORD: "root"
      
  adminer:
    image: adminer
    ports:
      - 8081:8080
