version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: usuarioroot@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
          
  db:
    image: postgres  
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres  
      #- POSTGRES_DB=test
      #- POSTGRES_USER= postgres 
      #- POSTGRES_PASSWORD=root       
    volumes:
      - ./data/db:/var/lib/postgresql/data
  #  dns:
  #    - 127.0.0.1
