# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres  
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres  
      #- POSTGRES_DB=test
      #- POSTGRES_USER= postgres 
      #- POSTGRES_PASSWORD=root       
    volumes:
      - ./data/db:/var/lib/postgresql/data
    dns:
      - 127.0.0.1

  
